### ISSUE TITLE
Error checking deps

### ISSUE THREAD

**Issue by kKen94** [drashland/dmm#55]
**Describe the bug**
```
deno run --allow-net --allow-read --allow-write https://deno.land/x/dmm@v1.1.4/mod.ts check
Gathering facts...
Reading deps.ts to gather your dependencies...
error: Uncaught TypeError: Cannot read property 'split' of undefined
        ? (dep.split("@" + importedVersion + "/")[1]).split("/")[0]
                                                      ^
    at Function.constructModulesDataFromDeps (https://deno.land/x/dmm@v1.1.4/src/services/module_service.ts:94:55)
    at async check (https://deno.land/x/dmm@v1.1.4/src/commands/check.ts:14:19)
    at async run (https://deno.land/x/dmm@v1.1.4/mod.ts:13:5)
    at async https://deno.land/x/dmm@v1.1.4/mod.ts:56:1
```

**To Reproduce**
1. Open root project
2. Launc dmm check

**Desktop (please complete the following information):**

- OS: Windows 10 and WSL2 Ubuntu

**Additional context**
Test repo link: https://github.com/kKen94/deno-test

**Comment by Guergeiro** [comment]
Hey @kKen94, thanks for your issue. We will address it as soon as possible!

**Comment by ebebbington** [comment]
@kKen94 can you paste the whole contents of your deps.ts file?

**Comment by kKen94** [comment]
> @kKen94 can you paste the whole contents of your deps.ts file?

Sure!!

```
export { Drash } from 'https://deno.land/x/drash@v1.2.3/mod.ts';
export { Dexter } from 'https://deno.land/x/drash_middleware@v0.4.1/dexter/mod.ts';
export { v4 } from 'https://deno.land/std@0.65.0/uuid/mod.ts';
export * as log from 'https://deno.land/std@0.65.0/log/mod.ts';
export { Paladin } from 'https://deno.land/x/drash_middleware@v0.4.1/paladin/mod.ts';
```

**Comment by ebebbington** [comment]
Ahhh so it's due to the regex that tries to get the imported version: `/(v)?[0-9].+[0-9].+[0-9]/g`, which is matching the `export { v4 }` bit (when it shouldn't), so `importedVersion` is `v4 } from 'https://...'`
